services:
  - type: web
    name: rn-herbal-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SMTP_HOST
        scope: run
      - key: SMTP_PORT
        scope: run
      - key: SMTP_SECURE
        scope: run
      - key: SMTP_USER
        scope: run
      - key: SMTP_PASS
        scope: run
      - key: MAIL_FROM
        scope: run
      - key: ORDER_NOTIFICATION_EMAIL
        scope: run
